# ----------------------- #
#      Main Configs       #
# ----------------------- #
encoding: "utf-8"
url: http://docs.w3cub.com
title: W3cubDocs
lang: en

# subtitle: A blogging framework for hackers.
author: w3cub
# simple_search: https://www.google.com/search
description: W3cubDocs is a based Github Pages service API documentation browser with 80+ docs including HTML, CSS, JavaScript, PHP, Ruby, Python, Go, C, C++, jQuery, and more.
# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
# date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
# subscribe_rss: 
# subscribe_email:
# RSS feeds can list your email address if you like
# email:

collections:
  docs:
    output: true
    permalink: /:path.html

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
# permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins_dir: plugins


titlecase: true       # Converts page and post titles to titlecase



# Google Analytics
google_analytics_tracking_id: UA-71174418-1

# Facebook Like
# facebook_like: false

# *.png application.js application.css application-dark.css

exclude:
    - assets/*
    - javascripts/*
    - stylesheets/*

include:
    - cpp/utility/program/_exit.html
    - javascript/global_objects/object/__definesetter__.html
    - javascript/global_objects/object/__definegetter__.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fco_005fbroadcast.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fimage_005fstatus.html
    - gnu_fortran~7/_005fgfortran_005fset_005foptions.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fget.html
    - gnu_fortran~7/_0025loc-as-an-rvalue.html
    - gnu_fortran~7/_005fgfortran_005fset_005fconvert.html
    - gnu_fortran~7/_005fgfortran_005fset_005fargs.html
    - gnu_fortran~7/_005fgfortran_005fset_005frecord_005fmarker.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005finit.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsync_005fmemory.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fnum_005fimages.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fco_005fmin.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005ffail_005fimage.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fderegister.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005ferror_005fstop.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fatomic_005fdefine.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsendget_005fby_005fref.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsync_005fimages.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005funlock.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fatomic_005fop.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005ffinish.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fatomic_005fcas.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005flock.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fis_005fpresent.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fthis_005fimage.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsendget.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fevent_005fquery.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fget_005fby_005fref.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fregister.html
    - gnu_fortran~7/_005fgfortran_005fset_005fmax_005fsubrecord_005flength.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fco_005fsum.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fevent_005fpost.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005ferror_005fstop_005fstr.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fatomic_005fref.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005ffailed_005fimages.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsync_005fall.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fco_005fmax.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsend_005fby_005fref.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fevent_005fwait.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fstopped_005fimages.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fsend.html
    - gnu_fortran~7/_005fgfortran_005fcaf_005fco_005freduce.html
    - gnu_fortran~7/_005fgfortran_005fset_005ffpe.html
    - gnu_fortran~7/_002exor_002e-operator.html
    - gcc~7/_0040encode.html
    - gcc~7/_005f_005fint128.html
    - gcc~7/_005f_005fatomic-builtins.html
    - gcc~7/_005f_005fsync-builtins.html
    - c/program/_exit.html
    - c/keyword/_complex.html
    - c/keyword/_alignas.html
    - c/keyword/_noreturn.html
    - c/keyword/_generic.html
    - c/keyword/_imaginary.html
    - c/keyword/_bool.html
    - c/keyword/_thread_local.html
    - c/keyword/_atomic.html
    - c/keyword/_static_assert.html
    - c/keyword/_alignof.html
    - python~2.7/library/_winreg.html
    - python~2.7/library/__future__.html
    - python~2.7/library/__builtin__.html
    - python~2.7/library/__main__.html
    - perl~5.26/functions/__package__.html
    - perl~5.26/functions/__line__.html
    - perl~5.26/functions/__sub__.html
    - perl~5.26/functions/__end__.html
    - perl~5.26/functions/__data__.html
    - perl~5.26/functions/__file__.html
    - haxe~cs/system/_appdomain.html
    - haxe~cs/system/runtime/interopservices/_modulebuilder.html
    - haxe~cs/system/runtime/interopservices/_attribute.html
    - haxe~cs/system/runtime/interopservices/_assemblyname.html
    - haxe~cs/system/runtime/interopservices/_module.html
    - haxe~cs/system/runtime/interopservices/_parameterbuilder.html
    - haxe~cs/system/runtime/interopservices/_methodbase.html
    - haxe~cs/system/runtime/interopservices/_customattributebuilder.html
    - haxe~cs/system/runtime/interopservices/_propertybuilder.html
    - haxe~cs/system/runtime/interopservices/_methodinfo.html
    - haxe~cs/system/runtime/interopservices/_fieldinfo.html
    - haxe~cs/system/runtime/interopservices/_enumbuilder.html
    - haxe~cs/system/runtime/interopservices/_eventinfo.html
    - haxe~cs/system/runtime/interopservices/_exception.html
    - haxe~cs/system/runtime/interopservices/_thread.html
    - haxe~cs/system/runtime/interopservices/_activator.html
    - haxe~cs/system/runtime/interopservices/_assemblybuilder.html
    - haxe~cs/system/runtime/interopservices/_memberinfo.html
    - haxe~cs/system/runtime/interopservices/_eventbuilder.html
    - haxe~cs/system/runtime/interopservices/_fieldbuilder.html
    - haxe~cs/system/runtime/interopservices/_parameterinfo.html
    - haxe~cs/system/runtime/interopservices/_propertyinfo.html
    - haxe~cs/system/runtime/interopservices/_signaturehelper.html
    - haxe~cs/system/runtime/interopservices/_methodbuilder.html
    - haxe~cs/system/runtime/interopservices/_constructorinfo.html
    - haxe~cs/system/runtime/interopservices/_typebuilder.html
    - haxe~cs/system/runtime/interopservices/_localbuilder.html
    - haxe~cs/system/runtime/interopservices/_type.html
    - haxe~cs/system/runtime/interopservices/_ilgenerator.html
    - haxe~cs/system/runtime/interopservices/_assembly.html
    - haxe~cs/system/runtime/interopservices/_constructorbuilder.html
    - symfony~3.3/symfony/bundle/securitybundle/security/_firewallmap.html
    - openjdk~8_web/org/omg/portableserver/_servantlocatorstub.html
    - openjdk~8_web/org/omg/portableserver/_servantactivatorstub.html
    - openjdk~8_web/org/omg/dynamicany/_dynarraystub.html
    - openjdk~8_web/org/omg/dynamicany/_dynenumstub.html
    - openjdk~8_web/org/omg/dynamicany/_dynunionstub.html
    - openjdk~8_web/org/omg/dynamicany/_dynvaluestub.html
    - openjdk~8_web/org/omg/dynamicany/_dynfixedstub.html
    - openjdk~8_web/org/omg/dynamicany/_dynanystub.html
    - openjdk~8_web/org/omg/dynamicany/_dynstructstub.html
    - openjdk~8_web/org/omg/dynamicany/_dynanyfactorystub.html
    - openjdk~8_web/org/omg/dynamicany/_dynsequencestub.html
    - openjdk~8_web/org/omg/corba/_idltypestub.html
    - openjdk~8_web/org/omg/corba/_policystub.html
    - openjdk~8_web/org/omg/stub/java/rmi/_remote_stub.html
    - openjdk~8_web/org/omg/cosnaming/_bindingiteratorimplbase.html
    - openjdk~8_web/org/omg/cosnaming/_namingcontextstub.html
    - openjdk~8_web/org/omg/cosnaming/_bindingiteratorstub.html
    - openjdk~8_web/org/omg/cosnaming/_namingcontextimplbase.html
    - openjdk~8_web/org/omg/cosnaming/_namingcontextextstub.html
    - dojo/dojo/selector/_loader.html
    - python~3.6/library/_dummy_thread.html
    - python~3.6/library/__future__.html
    - python~3.6/library/_thread.html
    - python~3.6/library/__main__.html

assets:
  # compress:
  #   css: false | true | default - development: false, production: true
  #   js: false | true | default - development: false, production: true
  autowrite: true
  # cache: false | directory | default: .asset-cache
  # cache_type: memory | filesystem | default: filesystem
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE >= 9"
  #

  assets:
    - "*.png" 
    - "application.js" 
    - "application.css" 
    - "application-dark.css"
  # compress:
  #   css: sass
  #   js: uglifier

  sources:
    - assets/images
    - assets/javascripts
    - assets/stylesheets

  # features:
  #   liquid: true | false | default: false
  #   integrity: true | false | default: false
  #   automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
  #   automatic_img_alt : true | false | default: true


# env: production

plugins: 
    - jekyll-assets
    # - jekyll-sitemap
    # - octopress-minify-html