# ----------------------- #
#      Main Configs       #
# ----------------------- #
encoding: "utf-8"
url: http://docs.w3cub.com
title: W3cubDocs
lang: en

# subtitle: A blogging framework for hackers.
author: w3cub
# simple_search: https://www.google.com/search
description: W3cubDocs is a based Github Pages service API documentation browser with 80+ docs including HTML, CSS, JavaScript, PHP, Ruby, Python, Go, C, C++, jQuery, and more.
# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
# date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
# subscribe_rss: 
# subscribe_email:
# RSS feeds can list your email address if you like
# email:

collections:
  docs:
    output: true
    permalink: /:path.html

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
# permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins_dir: plugins


titlecase: true       # Converts page and post titles to titlecase



# Google Analytics
google_analytics_tracking_id: UA-71174418-1

# Facebook Like
# facebook_like: false

# *.png application.js application.css application-dark.css

exclude:
    - assets/*
    - javascripts/*
    - stylesheets/*

assets:
  # compress:
  #   css: false | true | default - development: false, production: true
  #   js: false | true | default - development: false, production: true
  autowrite: true
  # cache: false | directory | default: .asset-cache
  # cache_type: memory | filesystem | default: filesystem
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE >= 9"
  #

  assets:
    - "*.png" 
    - "application.js" 
    - "application.css" 
    - "application-dark.css"
  # compress:
  #   css: sass
  #   js: uglifier

  sources:
    - assets/images
    - assets/javascripts
    - assets/stylesheets

  # features:
  #   liquid: true | false | default: false
  #   integrity: true | false | default: false
  #   automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
  #   automatic_img_alt : true | false | default: true


# env: production

gems: 
    - jekyll-assets
    # - jekyll-sitemap
    # - octopress-minify-html